### ISSUE TITLE
Pondus Legacy buggyness

### ISSUE THREAD

**Issue by lukawarren** [lukawarren/Lorien-Legacies#1]
Try flying after leaving a world where you were blessed with Pondus

**Comment by Blue20Boy17** [comment]
when it's not toggled, you still walk on water, and you start flying, and then you can't stop flying, just keep going up and up. when you turn it back on, however, the flying part is fixed. also, it shouldn't grant water breathing, because you're still above water...unless it's necessary for the code to work properly

**Comment by lukawarren** [comment]
Working on it now. Also need to fix localisation in the control menu regarding toggling it.

**Comment by lukawarren** [comment]
Yeah I can reproduce all those issues. Going to try a different approach to Pondus

**Comment by lukawarren** [comment]
Not sure if it's completely perfect, but I _might_ have solved the issue? It was hard to reproduce so I dunno, but from the looks of things the player doesn't float upwards anymore, and doesn't get water breathing.
