### ISSUE TITLE
Accelix still doesn't work with Pondus

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#36]
When you are on water with both pondus and accelix active you dont run fast

**Comment by lukawarren** [comment]
Duplicate of issue #18. 

Accelix can't _properly_ work with Pondus since the physics on water mean there is no friction, so any acceleration becomes exponential, the player zooms at a million blocks a second, then the world crashes...

I've tried to make it so that one does at least run a little faster with Accelix enabled. You did enable Accelix with the keybinding, didn't you? I believe the default key is semicolon or something.

**Comment by 1nsertTextHere** [comment]
ok
