### ISSUE TITLE
Mobs appeared highlighted

### ISSUE THREAD

**Issue by Blue20Boy17** [lukawarren/Lorien-Legacies#37]
When Fortem is enabled (and maybe other toggle-able Legacies), when you point at a mob, it becomes solid white, like the telekinesis highlighting thing.

**Comment by lukawarren** [comment]
Yup it's kinda on purpose (as in I _enabled_ it). It's what's become of Telekinesis at the moment (I was testing selecting entities and forgot to turn it off). Turns out selecting isn't working properly, it's weird. Only works at certain angles server-side. No idea why.

Anyway I'll disable telekinesis for now to fix it.
