### ISSUE TITLE
Legacy blesser issue (Survival legacy loading issue)

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#71]
The Legacy blesser does not work. Ive opened 4 new survival worlds and I haven't been assigned any legacies.

**Comment by lukawarren** [comment]
The legacy blesser does work, you just got unlucky. There's a bug in Survival where _sometimes_ there's a nullReferenceExcetion in the client proxy's player. It happens (I think) because in singleplayer the server can load before the client, and tell the client to go ahead and do stuff with the player, even though the client doesn't have the player yet. I suppose it's random cause it's a race condition.

**Comment by lukawarren** [comment]
Try in creative, the blesser should work.

**Comment by lukawarren** [comment]
Closing for now. If the solution doesn't work we can always re-open it.
