### ISSUE TITLE
Avex flying whilst mid-air

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#85]
Avex doesnt work if you jump then activate it. Im not sure if it is because the stamina runs out to quickly (which it still does), or if it doesn't work period.

**Comment by 1nsertTextHere** [comment]
actually, forget the stamina runs out to quickly thing.

**Comment by 1nsertTextHere** [comment]
but it still regenerates too quickly

**Comment by lukawarren** [comment]
Avex doesn't work mid-air because that way you could run out of stamina with Avex, fall to the ground, then activate it before you die, flying away to safety, which felt kinda cheaty. But I can adjust it so that you can jump off somewhere then fly probably. 

Really, these two things should be separate issues, or all the Avex enhancements should be put in one giant issue.

**Comment by lukawarren** [comment]
I'll post another issue for the stamina regeneration.

**Comment by lukawarren** [comment]
No longer a thing since the rewrite.
